<?php

namespace AppBundle\Repository;

/**
 * CotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Selection de l'année encours
     *
     * @author: Delrodie AMOIKON
     * @version v1.0 19/05/2017 04:05
     */
    public function getCotisationAnnee($cotisation)
    {
        //$em =$this->getEntityManager();
        $qb = $this->createQueryBuilder('c')
                   ->where('c.annee = :cotisation')
                   ->setParameter('cotisation', $cotisation);
        return $qb;
    }

    /**
     * Determination de la dernière cotisation enregistrée
     *
     * @author: Delrodie AMOIKON
     * @version: v1.0 20/05/2017 02:30
     */
    public function getDerniereCotisation()
    {
        /*$em = $this->getEntityManager();
        $qb = $em->createQuery('
                      SELECT c
                      FROM AppBundle:Cotisation c
                      ORDER BY c.id DESC
                  ')->setMaxResults(1);
                  ;
        return $qb->getSingleResult();*/

        $qb = $this->createQueryBuilder('c')
                 ->orderBy('c.id', 'DESC')
                 ->setMaxResults(1);
        if (($qb->getQuery()->getResult()) === []) {
           return 0;
        } else {
          return $qb->getQuery()->getSingleResult();
        }

    }

    /**
     * Liste decroissante des cotisations
     */
    public function findByAnneDESC()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.annee', 'DESC')
                    ->getQuery()->getResult()
            ;
    }
}
