<?php

namespace AppBundle\Repository;

/**
 * CotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Selection de l'année encours
     *
     * @author: Delrodie AMOIKON
     * @version v1.0 19/05/2017 04:05
     */
    public function getCotisationAnnee($cotisation)
    {
        //$em =$this->getEntityManager();
        $qb = $this->createQueryBuilder('c')
                   ->where('c.annee = :cotisation')
                   ->setParameter('cotisation', $cotisation);
        return $qb;
    }
}
