<?php

namespace AppBundle\Repository;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository
{
  /**
    * Selection du distrct concerné par l'enregistrement du groupe
    * Pour GroupeType.php
    *
    * @author: Delrodie AMOIKON
    * @version v1.0 16/05/2017 10:31
    */
    public function getDistrictNom($district)
    {
       //die($user);
        $em = $this->getEntityManager();

        $qb = $this->createQueryBuilder('d')
                   ->where('d.id = :district')
                   ->setParameter('district', $district);
         return $qb;
    }
}
