<?php

namespace AppBundle\Repository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  /**
    * Liste des utilisateurs sans Delrodie
    *
    * @author Delrodie AMOIKON
    * Date: 09/05/2017
    */
   public function getUser(){
     $em = $this->getEntityManager();
      $qb = $em->createQuery('
          SELECT u
          FROM AppBundle:User u
          WHERE u.username <> :nom
      ')
        ->setParameter('nom', 'delrodie')
      ;
      try {
          $result = $qb->getResult();

          return $result;

      } catch (NoResultException $e) {
          return $e;
      }
   }
}
